"""Conținutul paginilor generate: lucrări, domenii, ghiduri, întrebări.

Cifrele lucrărilor sunt cele din studiile de caz publicate pe medclyn.com
(citite pe 2 oct. 2026). Unde articolul nu spune ceva (echipă, localitate,
durată), câmpul rămâne gol: pagina nu inventează.

  old    adresa articolului pe medclyn.com, pentru redirect 301 și sursă
  area   m² placați, ca număr (pentru totaluri și sortare)
  ll     (lat, lon) când localitatea e cunoscută, pentru hartă
"""

DOMAINS = {
    'alimentar': dict(slug='industria-alimentara', name='Industria alimentară', short='alimentar'),
    'medical':   dict(slug='domeniul-medical', name='Spitale și clinici', short='medical'),
    'farma':     dict(slug='industria-farmaceutica', name='Industria farmaceutică', short='farmaceutic'),
    'cosmetic':  dict(slug='industria-cosmetica', name='Industria cosmetică', short='cosmetic'),
    'bucatarii': dict(slug='bucatarii-profesionale', name='Bucătării profesionale', short='bucătării'),
    'alte':      dict(slug='alte-domenii', name='Săli de sport, vestiare, școli', short='alte domenii'),
}

CASES = [
  dict(key='b37', slug='ursus-breweries-brasov', domain='alimentar', sector='Fabrică de bere',
       client='Ursus Breweries', place='Brașov', country='RO', ll=(45.65, 25.60), date='2022-12-20',
       old='ursus-romania-alege-placarea-antibacteriana-de-la-medclyn-b37',
       area=1000, extra=None, duration='40 de zile', team='12 oameni',
       stop='Linia n-a fost oprită. Lucrul printre utilaje a dus șantierul la 40 de zile.',
       before='Pereți și tavane în spații de producție, cu conducte și utilaje lipite de perete.',
       h1='Ursus Breweries: 1.000 m² placați printre conductele fabricii Ciucaș',
       story=[
         'La fabrica din Brașov, unde se face berea Ciucaș, pereții și tavanele din producție trebuiau refăcute. Ursus a comparat variantele de pe piață și a ales placarea MedClyn.',
         'Utilajele și instalațiile nu puteau fi demontate, iar linia nu putea fi oprită de tot. Între echipamente și perete rămânea foarte puțin loc, așa că plăcile au fost tăiate în bucăți mici și îmbinate în spatele țevilor.',
         'MedClyn o numește una dintre cele mai grele lucrări pe care le-a avut. Următoarele, după articolul lor, sunt celelalte fabrici ale grupului: București, Timișoara, Cluj.'],
       did=['Pereți și tavane în spațiile de producție', 'Plăci tăiate pe loc și îmbinate în spatele conductelor', 'Montaj cu linia în funcțiune'],
       quote=None),
  dict(key='b36', slug='abatorul-bona-avis-ianca', domain='alimentar', sector='Abator de pui',
       client='Abatorul de pui Bona Avis', place='Ianca, Brăila', country='RO', ll=(45.13, 27.47), date='2022-10-03',
       old='abatorul-de-pui-bona-avis-reconditioneaza-panourile-sandwich-cu-placile-medclyn-b36',
       area=616, extra=None, duration='10 zile', team='6–8 oameni',
       stop='Liniile automate de tranșare au mers 8 ore din 10. Echipa a lucrat după-amiaza și noaptea.',
       before='Panouri sandwich vechi de 13–15 ani, revopsite la fiecare 2–3 ani, pe care vopseaua nu mai ținea deloc.',
       h1='Bona Avis: 616 m² peste panouri sandwich, cu liniile de tranșare pornite',
       story=[
         'Abatorul din Ianca funcționează în foste fabrici, amenajate acum 13–15 ani cu panouri sandwich. De atunci, panourile au fost revopsite la fiecare 2–3 ani, până când vopseaua n-a mai ținut deloc.',
         'Placarea s-a lipit direct peste panouri. Producția nu s-a oprit: liniile de tranșare automată au mers cu două ore mai puțin pe zi, iar echipa MedClyn a lucrat în ture de după-amiază și noapte.',
         'Patronul a vrut să vadă un an cum se comportă sistemul. Dacă trece proba, urmează peste 3.000 m² de pereți și tavane în tot abatorul.'],
       did=['Placare peste panouri sandwich existente', 'Lucru în ture de după-amiază și noapte'],
       video='vd10', quote=None),
  dict(key='b35', slug='ayt-macelarie-bucuresti', domain='alimentar', sector='Măcelărie și market',
       client='AYT Măcelărie & Market', place='București', country='RO', ll=(44.43, 26.10), date='2022-08-31',
       old='ayt-macelarie-and-market-placheaza-peretii-cu-medclyn-b35',
       area=300, extra='50 ml bară de protecție', duration='2 zile', team='3 oameni', stop=None,
       before='Zidărie cu tencuială, glet și vopsea, crăpată de umiditate. Vopseaua se exfolia.',
       h1='AYT București: 300 m² de pereți crăpați, refăcuți în 2 zile',
       story=[
         'AYT e măcelărie, market și restaurant cu specific turcesc. În spațiile măcelăriei, umiditatea a crăpat pereții de zidărie, iar vopseaua a început să se exfolieze — un risc direct pentru carne.',
         'În prima etapă s-au refăcut porțiunile cele mai afectate, în principal pereți, plus 50 ml de bară de protecție. Restul spațiilor urmează când se alocă bugetul.'],
       did=['Placare peste zidărie tencuită și vopsită', 'Bară de protecție pe 50 ml'],
       quote=None),
  dict(key='b34', slug='elixir-dc-procesare-peste', domain='alimentar', sector='Procesare pește',
       client='Elixir DC', place=None, country='RO', ll=None, date='2022-07-06',
       old='unitatea-de-procesare-peste-elixir-dc-renoveaza-cu-medclyn-b34',
       area=70, extra='15 ml bară de protecție', duration='2 zile', team='2 oameni', stop=None,
       before='Panouri sandwich renovate de mai multe ori. După fiecare renovare, vopseaua se exfolia din nou și apărea rugina.',
       h1='Elixir DC: o încăpere de procesare a peștelui, scoasă din ciclul revopsirii',
       story=[
         'În procesarea peștelui se lucrează în umezeală permanentă. La Elixir DC, panourile sandwich fuseseră reabilitate de mai multe ori, dar vopseaua se exfolia din nou în scurt timp și apărea rugina.',
         'De data asta, 70 m² au fost placați cu sistemul complet, plus 15 ml de bară de protecție, în două zile, cu doi oameni.'],
       did=['Placare peste panouri sandwich', 'Bară de protecție pe 15 ml'],
       quote=None),
  dict(key='b33', slug='arena-group-farmaceutice', domain='farma', sector='Fabrică de medicamente',
       client='Arena Group', place='București', country='RO', ll=(44.43, 26.10), date='2022-06-22',
       old='arena-group-farmaceutice-testeaza-placile-antibacteriene-medclyn-b33',
       area=100, extra='30 ml bară de protecție', duration=None, team=None, stop=None,
       before='Holuri de trecere și o încăpere de producție.',
       h1='Arena Group: lucrarea de probă dinaintea renovării unei fabrici de medicamente',
       story=[
         'Arena Group produce medicamente vândute în farmaciile din țară și din străinătate. Înainte de o renovare mare la una dintre fabricile din București, conducerea a vrut să vadă rezultatul pe o suprafață mică.',
         'Contractul de probă: aproximativ 100 m² de pereți pe holuri și într-o încăpere de producție, plus 30 ml de bară de protecție. După probă, au urmat etapizat mai multe spații de producție.'],
       did=['Pereți pe holuri de trecere', 'O încăpere de producție', 'Bară de protecție pe 30 ml'],
       quote=None),
  dict(key='b32', slug='sagrod-darabani', domain='alimentar', sector='Abator și procesare carne',
       client='Sagrod', place='Darabani, Botoșani', country='RO', ll=(48.18, 26.59), date='2022-06-14',
       old='sagrod-renoveaza-fabrica-de-procesare-carne-b32',
       area=600, extra=None, duration='5 zile', team='7 oameni', stop=None,
       before='Panouri sandwich cu vopsea exfoliată și rugină.',
       h1='Sagrod Darabani: 600 m² în 5 zile, la recomandarea altor fabrici din zonă',
       story=[
         'Sagrod e abator și fabrică de procesare a cărnii în Darabani, cel mai nordic oraș al țării. Panourile sandwich din o parte a spațiilor de producție începuseră să ruginească.',
         'Recomandarea a venit de la alte fabrici din industria cărnii din nordul țării, unde MedClyn lucrase deja. 600 m² au fost gata în 5 zile, cu 7 oameni.'],
       did=['Placare peste panouri sandwich ruginite'],
       quote=None),
  dict(key='b31', slug='spitalul-orasenesc-cugir', domain='medical', sector='Spital public',
       client='Spitalul Orășenesc Cugir', place='Cugir, Alba', country='RO', ll=(45.84, 23.36), date='2022-05-31',
       old='spitalul-cugir-renoveaza-sala-de-chirurgie-cu-medclyn-b31',
       area=200, extra=None, duration='3 zile', team='4 oameni', stop=None,
       before='Sala de chirurgie și câteva încăperi aferente.',
       h1='Spitalul Cugir: sala de chirurgie placată în 3 zile',
       story=[
         'Renovarea unui spital public trece prin multă birocrație, iar o parte din lucrările medicale ale MedClyn din 2022 sunt sub acord de confidențialitate.',
         'Spitalul Orășenesc Cugir a acceptat să fie arătat: sala de chirurgie și încăperile din jur, 200 m², în 3 zile, cu 4 oameni.'],
       did=['Sala de chirurgie', 'Încăperi anexe'],
       video='vd11', quote=None),
  dict(key='b30', slug='sasha-vlad-vestiare', domain='alimentar', sector='Procesare carne de pui și curcan',
       client='Sasha & Vlad Company', place=None, country='RO', ll=None, date='2022-05-17',
       old='renovare-vestiare-fabrica-de-procesare-carne-sasha-and-vlad-company-b30',
       area=150, extra=None, duration=None, team=None, stop=None,
       before='Vestiare și holuri din zidărie tencuită, cu glet și vopsea lavabilă, care se deteriorau.',
       h1='Sasha & Vlad: vestiarele, ca probă pentru panourile din toată fabrica',
       story=[
         'Fabrica procesează carne de pui și curcan din 2007. Panourile sandwich din producție tocmai fuseseră revopsite. Vestiarele și holurile, din zidărie cu vopsea lavabilă, se deteriorau.',
         'Cei aproximativ 150 m² din vestiare au fost și un test. Vopseaua de pe panouri nu ține mai mult de 1–2 ani, iar rezultatul din vestiare i-a convins pe patroni să placheze și panourile din toată fabrica.'],
       did=['Vestiare', 'Holuri de trecere'],
       quote=None),
  dict(key='b29', slug='vlasie-company-cascaval', domain='alimentar', sector='Fabrică de cașcaval',
       client='Vlasie Company', place=None, country='RO', ll=None, date='2022-05-03',
       old='fabrica-de-cascaval-vlasie-company-reconditioneaza-panourile-sandwich-cu-sistemul-medclyn-b29',
       area=400, extra=None, duration='4 zile', team='6 oameni', stop=None,
       before='Panouri sandwich montate în 2014, ruginite și cu vopseaua exfoliată după câțiva ani.',
       h1='Vlasie Company: au văzut lucrarea de la Solomonescu, apoi au comandat 400 m²',
       story=[
         'Vlasie face cașcaval tradițional din lapte natural. Spațiile, construite în 2014 din panouri sandwich, ruginiseră după câțiva ani.',
         'Revopsirea însemna oprirea lucrului și o vopsea care, ca și înainte, n-ar fi ținut mai mult de 2–3 ani. Conducerea a mers întâi la Lactate Solomonescu, să vadă placarea făcută acolo în 2021, și abia apoi a comandat.'],
       did=['Placare peste panouri sandwich'],
       quote=None),
  dict(key='b28', slug='clinica-medicala-200-mp-o-zi', domain='medical', sector='Clinică medicală',
       client='Clinică medicală din România', place=None, country='RO', ll=None, date='2022-04-20', confidential=True,
       old='standarde-inalte-de-igiena-si-sterilitate-la-clinica-medicala-din-romania-b28',
       area=200, extra=None, duration='1 zi', team='4 oameni', stop=None,
       before='Pereți și tavane care arătau foarte rău.',
       h1='Clinică medicală: 200 m² placați într-o singură zi',
       story=[
         'Numele clinicii nu e publicat, din motive de confidențialitate. Cifrele sunt: 200 m² de pereți, o zi de lucru, 4 oameni.',
         'Accesoriile de montaj — colțare, îmbinări, baghete — izolează placa de stratul de dedesubt, așa că și un perete în stare proastă iese neted și etanș.'],
       did=['Pereți și tavane', 'Colțare și îmbinări etanșe'],
       quote=None),
  dict(key='b27', slug='hotel-anna-targu-jiu', domain='bucatarii', sector='Bucătărie de hotel',
       client='Hotel Anna', place='Târgu Jiu', country='RO', ll=(45.04, 23.27), date='2022-04-06',
       old='hotel-anna-renoveaza-bucataria-cu-placi-antibacteriene-medclyn-b27',
       area=100, extra=None, duration='2 zile', team='3 oameni', stop=None,
       before='Bucătăria hotelului, la renovare.',
       h1='Hotel Anna, Târgu Jiu: bucătăria hotelului în 2 zile',
       story=[
         'Hotelul face parte din lanțul Crescendo. La renovarea bucătăriei, proprietarii au cerut ceva modern, curat și luminos.',
         'Aproximativ 100 m², 3 oameni, 2 zile. Placa albă lucioasă a fost pusă lângă tavanele vopsite în negru.'],
       did=['Pereții bucătăriei'],
       quote=None),
  dict(key='b26', slug='panouri-sandwich-sibiu', domain='alimentar', sector='Spații de producție alimentară',
       client='Spații de producție din județul Sibiu', place='județul Sibiu', country='RO', ll=(45.79, 24.15), date='2022-03-31', confidential=True,
       old='renovare-panouri-sandwich-la-carmangerie-din-sibiu-b26',
       area=2000, extra=None, duration=None, team=None, stop=None,
       before='Panouri sandwich cu rugină și vopsea exfoliată.',
       h1='Sibiu: 2.000 m² de panouri sandwich, pentru o firmă care le reabilita',
       story=[
         'Cererea a venit de la o firmă care montează și reabilitează panouri sandwich. Problema ei cea mai mare era tocmai rugina și vopseaua exfoliată de pe panourile pe care le întreținea.',
         'Împreună au placat aproximativ 2.000 m² în mai multe spații de producție din județul Sibiu. Firma n-a vrut să-i fie publicat numele.'],
       did=['Placare peste panouri sandwich, în mai multe spații de producție'],
       quote=None),
  dict(key='b25', slug='pomarom-procesare-melci', domain='alimentar', sector='Procesare melci, export în Franța',
       client='Pomarom', place=None, country='RO', ll=None, date='2022-03-11',
       old='fabrica-de-procesare-melci-reconditioneaza-panouri-sandwich-cu-medclyn-b25',
       area=1200, extra=None, duration='4 zile', team='10 oameni', stop=None,
       before='Panouri sandwich în spații cu temperaturi mari, umezeală și abur. Revopsirea nu ținea mai mult de 1–2 ani.',
       h1='Pomarom: 1.200 m² în 4 zile, în loc de încă o revopsire',
       story=[
         'Pomarom recoltează și procesează melci din 1993 și exportă mai ales în Franța. În zonele de producție se lucrează la cald, în abur și umezeală.',
         'A venit din nou rândul panourilor sandwich. În locul revopsirii, care ține 1–2 ani, au ales placarea: 1.200 m² de pereți și tavane, în 4 zile, cu 10 oameni.'],
       did=['Pereți și tavane peste panouri sandwich'],
       quote=None),
  dict(key='b24', slug='monor-lactate-bistrita-nasaud', domain='alimentar', sector='Fabrică de lactate',
       client='Lactate Monor', place='Monor, Bistrița-Năsăud', country='RO', ll=(46.95, 24.70), date='2022-03-04',
       old='renovare-fabrica-de-lapte-monor-placi-antibacteriene-renovare-laptarie-medclyn-placi-medclyn-pret-placi-medclyn-b24',
       area=350, extra=None, duration='5 zile', team='6 oameni', stop=None,
       before='Mai multe camere frigorifice și holuri.',
       h1='Monor: camerele frigorifice ale fabricii de lapte, 350 m² în 5 zile',
       story=[
         'Produsele Monor se vând în mai multe lanțuri de supermarketuri. La întreținerea periodică, fabrica a ales să placheze aproximativ 350 m² de pereți și tavane.',
         'Au fost mai multe camere frigorifice și holuri, gata în 5 zile, cu 6 oameni.'],
       did=['Camere frigorifice', 'Holuri'],
       quote=None),
  dict(key='b23', slug='abatorul-safir', domain='alimentar', sector='Abator de pui',
       client='Abatorul Safir', place=None, country='RO', ll=None, date='2022-02-28',
       old='abatorul-de-pui-safir-utilizeaza-sistemul-medclyn-b23',
       area=85, extra=None, duration='1 zi', team='3 oameni', stop=None,
       before='Panouri sandwich ruginite în zona de tranșare, renovate periodic la 3–4 ani.',
       h1='Abatorul Safir: zona de tranșare, într-o zi',
       story=[
         'Familia Safir crește, taie și livrează pui de peste 70 de ani. În zonele spălate cu apă sub presiune, abur și detergenți, panourile sandwich ruginiseră din nou.',
         'Prima etapă a fost spațiul de tranșare, cel mai expus ruginii: aproximativ 85 m², o zi, 3 oameni. Celelalte zone urmează.'],
       did=['Pereții spațiului de tranșare'],
       video='vd9', quote=None),
  dict(key='b22', slug='souflet-malt-buzau', domain='alimentar', sector='Fabrică de malț',
       client='Souflet Malt', place='Buzău', country='RO', ll=(45.15, 26.82), date='2022-02-22',
       old='demo-medclyn-la-fabrica-de-malt-souflet-malt-b22',
       area=100, extra=None, duration='1 zi', team='3 oameni', stop=None,
       before='Panouri sandwich deloc vechi, ruginite de la spălările dese.',
       h1='Souflet Malt: testul pe porțiunile cele mai ruginite',
       story=[
         'Fabrica de malț din Buzău livrează producătorilor de bere din România. Pereții se spală des, iar panourile sandwich, deși noi, ruginiseră.',
         'Pentru că sistemul era nou în România, Souflet a cerut întâi un test: o hală placată de la pardoseală până la 1 m înălțime, aproximativ 100 m² într-o zi.'],
       did=['Placare de la pardoseală până la 1 m, pe porțiunile ruginite'],
       quote=None),
  dict(key='b21', slug='lactate-solomonescu-botosani', domain='alimentar', sector='Fabrică de lactate',
       client='Lactate Solomonescu', place='Botoșani', country='RO', ll=(47.75, 26.67), date='2022-02-10',
       old='lactate-solomonescu-renoveaza-tavanele-cu-medclyn-b21',
       area=400, extra='100 ml plintă', duration='5 zile', team='4 oameni', stop=None,
       before='Tavane din panouri sandwich într-o încăpere cu abur aproape toată ziua. Vopseaua se exfolia și apăruse rugina.',
       h1='Lactate Solomonescu: tavanele căzute la auditul supermarketurilor',
       story=[
         'Problema tavanelor a ieșit la inspecțiile unor lanțuri mari de supermarketuri, care primesc produsele doar dacă fabrica e bine pusă la punct.',
         'În încăperea unde se face cașcavalul, mașinile scot abur aproape toată ziua. Panourile sandwich de pe tavan se exfoliau și ruginiseră. S-au placat 300 m² de tavane și 100 m² de pereți, plus 100 ml de plintă, în 5 zile.'],
       did=['300 m² de tavane', '100 m² de pereți', 'Plintă pe 100 ml'],
       video='vd6', quote=None),
  dict(key='b20', slug='swiss-caps-romania', domain='farma', sector='Fabrică de capsule gelatinoase',
       client='Swiss Caps România', place='Prahova', country='RO', ll=(44.94, 26.02), date='2022-01-30',
       old='fabrica-de-medicamente-swiss-caps-romania-foloseste-placi-antibacteriene-medclyn-b20',
       area=350, extra='120 ml plintă și bară de protecție', duration='3 zile', team='5 oameni',
       stop='Lucrul se face în concediile colective, când producția e redusă.',
       before='Fabrică deschisă în 2003–2004, la prima renovare mare.',
       h1='Swiss Caps România: fabrica de capsule se renovează în concedii',
       story=[
         'Swiss Caps face capsule gelatinoase și ambalaje pentru medicamente. Fabrica din Prahova a fost deschisă în 2003–2004 și a ajuns la vremea renovărilor.',
         'Toată fabrica se face etapizat, în perioadele de concediu. Prima etapă: 350 m² și 120 ml de plintă și bară de protecție, în 3 zile.'],
       did=['Pereți în spațiile de producție', 'Plintă și bară de protecție pe 120 ml'],
       quote=('Suntem foarte mulțumiți de rezultate și urmează să continuăm renovările atunci când va fi posibil.', 'Swiss Caps România')),
  dict(key='b18', slug='carmangeria-fazakas-prodcarmi', domain='alimentar', sector='Carmangerie',
       client='Fazakas Prodcarmi', place='Târgu Mureș', country='RO', ll=(46.54, 24.56), date='2022-01-16',
       old='carmangeria-fazakas-prodcarmi-lucrari-de-renovare-b18',
       area=400, extra=None, duration='o săptămână', team=None,
       stop='Lucrul s-a făcut după programul carmangeriei, de la 16:00 până la 2–3 dimineața.',
       before='Panouri sandwich puse cu 4–5 ani înainte, deja degradate de spălările cu presiune. DSV-ul atenționase fabrica.',
       h1='Fazakas Prodcarmi: atenționați de DSV, 400 m² în nopțile unei săptămâni',
       story=[
         'În 2021, la un control DSV, fabrica de mezeluri din Târgu Mureș a fost atenționată că nu mai respectă normele de igienă. Panourile sandwich montate cu 4–5 ani înainte nu rezistaseră spălărilor cu presiune.',
         'Carmangeria nu se putea opri, așa că echipa a lucrat după program, de la 16:00 până la 2–3 dimineața: aproximativ 400 m² de pereți și tavane, într-o săptămână. Patronul a rezervat prin contract încă o etapă pentru anul următor.'],
       did=['Pereți și tavane în sălile de tranșare și ambalare', 'Lucru în tura de noapte'],
       video='vd2',
       quote=('Pe durata lucrărilor MedClyn, șantierul a fost foarte curat, timpul de execuție mi s-a părut extrem de rapid comparativ cu ce am mai experimentat anii trecuți cu alte sisteme de renovare, iar prețul este unul extrem de avantajos.', 'Carmangeria Fazakas Prodcarmi')),
  dict(key='b17', slug='lactate-bradet-arges', domain='alimentar', sector='Fabrică de lactate',
       client='Lactate Brădet', place='Brădet, Argeș', country='RO', ll=(45.37, 24.80), date='2021-08-07',
       old='lactate-bradet-renoveaza-peste-1000-mp-cu-medclyn-b17',
       area=1000, extra=None, duration='4 săptămâni', team='5 oameni',
       stop='Fabrica a oprit pe rând câte o zonă. Lucrul s-a făcut ziua și uneori noaptea.',
       before='Pe multe porțiuni, stratul-suport nu era destul de rezistent și a trebuit curățat înainte.',
       h1='Lactate Brădet: o zonă de probă, apoi toată fabrica',
       story=[
         'După o zonă de probă, patronul, Marius Badea, a hotărât să placheze aproape toată fabrica: peste 1.000 m² de pereți și tavane.',
         'Lucrarea a durat aproape o lună. Pe multe porțiuni, suportul pereților și tavanelor nu era destul de rezistent; montată peste el, placa n-ar fi putut primi garanția de 20 de ani, așa că a fost curățat întâi. Accesul printre instalațiile de lactate a fost greu.'],
       did=['Demontarea și remontarea echipamentelor de pe pereți', 'Îndepărtarea suportului slab', 'Pereți și tavane', 'Colțare interioare rotunjite și etanșe', 'Colțare exterioare din inox sau PVC'],
       video='vd7',
       quote=('Am placat aproape 1000 de m² de pereți și tavane, și mă declar foarte mulțumit de rezultatul final. Montajul s-a realizat într-un timp record, aș spune.', 'Marius Badea, patron Lactate Brădet')),
  dict(key='b16', slug='linie-imbuteliere-miere-dambovita', domain='alimentar', sector='Îmbuteliere miere',
       client='Linie de îmbuteliere de miere', place='Dâmbovița', country='RO', ll=(44.93, 25.46), date='2021-05-01',
       old='linie-de-imbuteliere-de-miere-amenajata-cu-placi-antibacteriene-medclyn-b16',
       area=300, extra=None, duration='circa 3 săptămâni', team='2–3 oameni', stop=None,
       before='Clădire nouă, proiectată inițial pentru alt scop. DSV a respins vopseaua „lavabilă” și a cerut faianță fără rosturi.',
       h1='Linia de miere din Dâmbovița: DSV a refuzat vopseaua lavabilă',
       story=[
         'Un producător de miere voia să-și îmbutelieze singur marfa. La DSV i s-a spus clar: pereții trebuie să fie netezi și lucioși, ușor de spălat. Vopseaua „lavabilă” nu se aprobă, iar faianța trebuie montată fără rosturi, adică rectificată, mult mai scumpă.',
         'Văzuse plăcile antibacteriene pe când lucra în Franța. S-au placat aproximativ 300 m², cu 2–3 oameni, în circa trei săptămâni, pentru că proprietarul nu se grăbea.'],
       did=['Pereții liniei de îmbuteliere'],
       video='vd3', quote=None),
  dict(key='b15', slug='sanofi-centru-cercetare-paris', domain='farma', sector='Laborator de cercetare vaccinuri',
       client='Sanofi', place='Paris', country='FR', ll=None, date='2021-03-08',
       old='centrul-de-cercetare-medicala-sanofi-monteaza-placi-antibacteriene-medclyn-b15',
       area=600, extra=None, duration='4 săptămâni', team='5 oameni',
       stop='Ziua, cu oprirea pe rând a câte unui sector al centrului.',
       before='Laborator de cercetare pentru vaccinuri, cu protocol de securitate strict.',
       h1='Sanofi, Paris: 600 m² într-un laborator de vaccinuri, cu 5 oameni verificați',
       story=[
         'Sanofi a cerut documentele tuturor angajaților MedClyn și i-a verificat prin serviciile franceze de securitate. Au fost acceptați doar 5 oameni.',
         'La fiecare trecere dintr-un sector în altul, de zeci de ori pe zi, urma control corporal. Așa a ajuns lucrarea de 600 m² la patru săptămâni. Unul dintre motivele alegerii, după MedClyn: curățenia din timpul lucrului, critică într-un laborator.'],
       did=['Demontarea și remontarea echipamentelor de pe pereți', 'Pereți și tavane', 'Plinte cu etanșare pentru dezinfectanții din cercetare', 'Colțare interioare rotunjite', 'Colțare exterioare din inox'],
       quote=None),
  dict(key='b14', slug='the-bistrot-benoit-luvru', domain='bucatarii', sector='Restaurant',
       client='The Bistrot Benoit', place='Luvru, Paris', country='FR', ll=None, date='2021-03-07',
       old='medclyn-monteaza-placi-antibacteriene-in-restaurantul-the-bistrot-benoit-luvru-paris-b14',
       area=500, extra=None, duration='2 săptămâni', team='10 oameni',
       stop='Restaurantul n-a închis deloc.',
       before='Faianță care se desprindea și rosturi care nu se mai puteau curăța. Tavane casetate.',
       h1='The Bistrot Benoit, Luvru: 500 m² fără să închidă restaurantul',
       story=[
         'Restaurantul e chiar sub piramida inversă a Luvrului. Faianța din bucătărie și din depozite începuse să cadă, iar rosturile se murdăriseră până dincolo de curățat. Tavanele casetate arătau la fel.',
         'Pereții au fost placați, iar plăcile din tavanele casetate au fost înlocuite cu plăci MedClyn. Restaurantul a funcționat tot timpul.'],
       did=['Pereții bucătăriei și ai camerelor frigorifice', 'Plăcile tavanelor casetate, înlocuite', 'Plinte cu etanșare', 'Plintă de protecție la înălțimea cărucioarelor'],
       quote=None),
  dict(key='b13', slug='laduree-champs-elysees', domain='bucatarii', sector='Restaurant',
       client='Ladurée', place='Champs-Élysées, Paris', country='FR', ll=None, date='2021-03-07',
       old='ladureeparis-restaurant-de-lux-de-pe-champs-elysees-renoveaza-bucataria-cu-medclyn-b13',
       area=400, extra=None, duration='5–6 zile', team='10, apoi 5 oameni',
       stop='200 m² într-o noapte de 12–14 ore, înaintea controlului de a doua zi.',
       before='Bucătărie la subsol, cu mucegai și igrasie. Unii pereți au trebuit dărâmați și refăcuți.',
       h1='Ladurée, Champs-Élysées: 200 m² într-o noapte, înaintea controlului',
       story=[
         'Patronul a aflat că a doua zi vine controlul, după reclamații ale clienților. Bucătăria de la subsol era într-o stare proastă.',
         'Într-o singură noapte, de 12–14 ore, zece oameni au placat aproximativ 200 m² de pereți și tavane în bucătăria principală. Nu tot până la ultimul detaliu, dar destul ca restaurantul să nu fie închis. Restul, încă 200 m², s-a terminat în 5–6 zile.'],
       did=['Pereți dărâmați și refăcuți unde mucegaiul ajunsese prea adânc', 'Pereți și tavane', 'Plinte cu etanșare', 'Colțare din inox'],
       quote=None),
  dict(key='b12', slug='chai-33-paris-bercy', domain='bucatarii', sector='Restaurant de volum mare',
       client='Chai 33', place='Paris Bercy', country='FR', ll=None, date='2021-03-07',
       old='restaurant-chai-33-renoveaza-bucatariile-profesionale-cu-medclyn-b12',
       area=2500, extra=None, duration='3 săptămâni', team='15 oameni, în 2 echipe',
       stop='Șantier non-stop: 5 oameni ziua, 10 noaptea. Restaurantul a funcționat.',
       before='Bucătării și 5 camere frigorifice la subsol, care nu mai treceau evaluarea internă.',
       h1='Chai 33, Paris Bercy: 2.500 m² în 3 săptămâni, cu restaurantul deschis',
       story=[
         'Restaurantul de lângă arena din Bercy și-a făcut singur evaluarea și a decis să renoveze înainte de controale și amenzi.',
         'Peste 2.500 m² în bucătării și în 5 camere frigorifice, la subsol, cu acces pe scări înguste. Șantierul a mers non-stop, în două echipe.'],
       did=['Pereții bucătăriilor', '5 camere frigorifice', 'Plinte cu etanșare', 'Colțare din inox'],
       quote=None),
  dict(key='b11', slug='nestle-atelier-ciocolata-franta', domain='alimentar', sector='Atelier de ciocolată',
       client='Nestlé', place='Franța', country='FR', ll=None, date='2021-03-07',
       old='nestle-renoveaza-cu-medclyn-un-atelier-de-productie-de-ciocolata-b11',
       area=250, extra=None, duration='7 zile', team='5 oameni', stop=None,
       before='Atelier de producție cu echipamente, sprinklere și ventilație pe pereți și tavan.',
       h1='Nestlé: atelierul de ciocolată, cu sprinklerele demontate și puse la loc',
       story=[
         'Într-una dintre fabricile din Franța, Nestlé a ales placarea pentru un atelier de producție a ciocolatei: aproximativ 250 m², 7 zile, 5 oameni.',
         'Partea grea a fost demontarea și remontarea echipamentelor, a instalației de stingere (țevi și sprinklere) și a ventilației. Managerii fabricii au apreciat exact asta.'],
       did=['Demontarea și remontarea echipamentelor, sprinklerelor și ventilației', 'Pereți și tavane'],
       quote=None),
  dict(key='b10', slug='fabrica-aditivi-alimentari-amendata', domain='alimentar', sector='Fabrică de aditivi alimentari',
       client='Fabrică de aditivi alimentari', place=None, country=None, ll=None, date='2021-03-07', confidential=True,
       old='fabrica-de-chimicale-alimentare-amendata-pentru-nerespectarea-normelor-b10',
       area=4000, extra=None, duration='4 săptămâni', team='15 oameni', stop=None,
       before='Panouri sandwich ruginite, cu vopsea decojită și bucăți desprinse. Amendă la control.',
       h1='Fabrica de aditivi amendată: 4.000 m² în 4 săptămâni',
       story=[
         'Proprietarul ajunsese la „merge și așa”: rugină, vopsea decojită, pe alocuri bucăți de panou desprinse. Odată ce vopseaua originală a unui panou cedează, orice strat pus peste ea cedează și mai repede.',
         'O amendă usturătoare l-a trimis să caute altceva decât revopsirea din doi în doi ani. Au urmat aproximativ 4.000 m², în 4 săptămâni, cu 15 oameni.'],
       did=['Pereți peste panouri sandwich', 'Plinte cu etanșare', 'Colțare din inox', 'Plintă de protecție la înălțimea utilajelor mobile'],
       quote=None),
  dict(key='b9', slug='fabrica-mezeluri-2000-mp', domain='alimentar', sector='Fabrică de mezeluri',
       client='Fabrică de mezeluri', place=None, country=None, ll=None, date='2021-03-07', confidential=True,
       old='fabrica-de-mezeluri-alege-igiena-si-siguranta-alimentara-cu-sistemul-medclyn-b9',
       area=2000, extra=None, duration='3 săptămâni', team='15 oameni, în 3 echipe',
       stop='Fabrica n-a oprit deloc. O echipă ziua, două noaptea, printre angajați.',
       before='Panouri sandwich în spațiile de malaxare, încă decente, dar cu vopsea exfoliată și rugină.',
       h1='Fabrică de mezeluri: 2.000 m², pereți de 4,5 m, producția pornită',
       story=[
         'Spațiile arătau decent. Motivul renovării a fost metoda: lucru fără oprirea fabricii, înainte ca autoritățile să ceară ceva.',
         'Pereți de 4,5 m, schele printre utilaje, o echipă ziua și două noaptea. 2.000 m² în trei săptămâni.'],
       did=['Pereți de 4,5 m peste panouri sandwich', 'Plinte cu etanșare pentru spălare sub presiune', 'Colțare exterioare din inox, 15×15 cm'],
       quote=None),
  dict(key='b8', slug='clinica-cardiologie-paris', domain='medical', sector='Clinică privată de cardiologie',
       client='Clinică de cardiologie', place='Paris', country='FR', ll=None, date='2021-03-07',
       old='amenajare-clinica-de-cardiologie-cu-sistemul-medclyn-b8',
       area=600, extra=None, duration='3 săptămâni', team='10 oameni', stop=None,
       before='Un apartament de aproape 150 m² lângă Arcul de Triumf, transformat în clinică.',
       h1='Clinică de cardiologie, Paris: fără tencuială și glet, direct pe rigips',
       story=[
         'Doi asociați au cumpărat un apartament lângă Arcul de Triumf, ca să-l transforme în clinică. S-au demolat pereți, s-a recompartimentat și s-a refăcut instalația electrică.',
         'Placa s-a lipit direct pe rigips brut, cărămidă și BCA, deci n-a mai fost nevoie de tencuială, glet și zugrăveală. Montată pe orizontală, fără îmbinări verticale. La 3 săptămâni de la început, clinica putea primi aparatura.'],
       did=['Recompartimentare', 'Instalație electrică', 'Pereți și tavane, plăci pe orizontală', 'Plintă de protecție albastră'],
       quote=None),
  dict(key='b7', slug='sala-de-sport-liceu', domain='alte', sector='Sală de sport, vestiare, bucătărie',
       client='Centru sportiv al unui liceu', place=None, country=None, ll=None, date='2021-03-07', confidential=True,
       old='sala-de-sport-respecta-din-nou-normele-legale-datorita-sistemului-medclyn-b7',
       area=500, extra=None, duration='5 zile', team='8–10 oameni', stop=None,
       before='Vopsea exfoliată și faianță care cădea, după spălările obligatorii.',
       h1='Sala de sport a unui liceu: plăci de 4–5 m, fără nicio îmbinare verticală',
       story=[
         'La control, centrul sportiv încălca mai multe norme de igienă în sală, vestiare și bucătărie. Spălările dese exfoliaseră vopseaua și desprinseseră faianța.',
         'Cerința: cât mai puține îmbinări, ca soluțiile de spălare să nu intre în perete. Plăcile de 4–5 m s-au montat pe orizontală, fără nicio îmbinare verticală, cu plinta de protecție la jumătatea peretelui.'],
       did=['Sală de sport, vestiare, bucătărie', 'Plăci de 4–5 m montate pe orizontală', 'Plintă de protecție la jumătatea peretelui'],
       quote=None),
  dict(key='b6', slug='bucatarie-liceu-privat', domain='bucatarii', sector='Bucătărie și sală de mese școlară',
       client='Liceu privat', place=None, country=None, ll=None, date='2021-03-07', confidential=True,
       old='liceu-renoveaza-bucataria-restaurant-cu-medclyn-b6',
       area=200, extra=None, duration='7 zile', team='5 oameni',
       stop='Bucătăria a funcționat parțial.', before='Bucătăria și sălile de mese ale elevilor.',
       h1='Liceu privat: bucătăria elevilor, 200 m² în 7 zile',
       story=['Directorul a vrut mai multă siguranță alimentară pentru elevii care mănâncă la cantina școlii. S-au dărâmat câțiva pereți despărțitori, s-au ridicat alții și s-au placat bucătăria și sălile de mese.'],
       did=['Pereți despărțitori refăcuți', 'Bucătărie și săli de mese', 'Colțare exterioare din inox'],
       quote=None),
  dict(key='b5', slug='bucatarie-catering', domain='bucatarii', sector='Catering',
       client='Firmă de catering', place=None, country=None, ll=None, date='2021-03-04', confidential=True,
       old='amenajare-bucatarie-catering-placare-pereti-b5',
       area=200, extra=None, duration='4 zile', team='4 oameni', stop='Bucătăria a stat 4 zile.',
       before='Faianță cu rosturi și panouri sandwich. Somație la control, la doi ani de la deschidere.',
       h1='Catering: somați după doi ani pentru faianța cu rosturi',
       story=[
         'Autorizația de funcționare a fost dată cu faianță cu rosturi. La doi ani de la deschidere, la primul control serios, rosturile murdare n-au mai trecut, iar firma a fost somată să renoveze.',
         'Aproximativ 200 m² de pereți și tavane, în 4 zile, cu bucătăria oprită.'],
       did=['Pereți și tavane', 'Plinte cu etanșare pentru spălare sub presiune', 'Colțare din inox'],
       quote=None),
  dict(key='b4', slug='restaurant-bianco-paris', domain='bucatarii', sector='Restaurant',
       client='Bianco', place='Paris', country='FR', ll=None, date='2021-03-04',
       old='restaurantul-bianco-paris-placheaza-peretii-bucatariei-cu-medclyn-b4',
       area=150, extra=None, duration='5 zile', team='2–3 oameni',
       stop='Doar noaptea. Dimineața, bucătăria pornea normal.',
       before='Bucătărie mică, la subsol, cu umezeală, igrasie și mucegai.',
       h1='Bianco, Paris: bucătăria de la subsol, placată doar noaptea',
       story=[
         'Restaurant italian cu mulți clienți și o bucătărie mică la subsol, unde umezeala vine de la sine.',
         'Lucrul s-a făcut doar noaptea. Frigiderele, hotele și malaxoarele erau scoase din funcțiune seara și repornite dimineața, ca personalul să gătească normal.'],
       did=['Pereți și tavane', 'Instalație electrică refăcută', 'Plintă de protecție la înălțimea cărucioarelor'],
       quote=None),
  dict(key='b3', slug='abator-rennes', domain='alimentar', sector='Abator',
       client='Abator din Rennes', place='Rennes', country='FR', ll=None, date='2021-03-04',
       old='norme-si-conditii-pentru-abator-restabilite-cu-sistemul-medclyn-b3',
       area=1000, extra=None, duration='10 zile', team='8 oameni, în 2 echipe',
       stop='Linia n-a oprit. Tura de zi a lucrat printre muncitorii abatorului.',
       before='Amendă și somație de renovare urgentă, sub amenințarea închiderii.',
       h1='Abator din Rennes: amendat, apoi 1.000 m² în 10 zile cu linia pornită',
       story=[
         'Abatorul fusese amendat și somat să renoveze urgent. Proprietarul mai renovase cu trei ani înainte, cu linia oprită, iar pereții se degradau din nou.',
         'Pereți de 4 m, mașini peste tot. Pe tavane s-au pus plăci în fâșii, îmbinate cu garnitură flexibilă, pentru că acolo spațiul era prea strâmt pentru plăcile mari. La controlul de după, proprietarul a fost felicitat.'],
       did=['Pereți de 4 m', 'Tavane din plăci în fâșii, cu garnitură flexibilă', 'Plinte cu etanșare', 'Colțare din inox'],
       quote=None),
  dict(key='b2', slug='abator-curcani-bignan', domain='alimentar', sector='Abator de curcani',
       client='Abator de curcani', place='Bignan', country='FR', ll=None, date='2021-02-28',
       old='abator-de-curcani-renovat-cu-medclyn-b2',
       area=2000, extra=None, duration='3 săptămâni', team='8–9 oameni',
       stop='Abatorul a funcționat tot timpul.',
       before='Hale vechi din panouri sandwich, cu vopsea exfoliată și rugină. Neconform la control.',
       h1='Abator de curcani, Bignan: peste 2.000 m² fără oprire',
       story=[
         'La control, abatorul nu mai respecta normele: panourile sandwich din halele vechi se exfoliaseră și ruginiseră de la spălări.',
         'Peste 2.000 m² de pereți și tavane, colțare și plinte de etanșare, colțare de protecție din inox și uși de silicon pe trecerile cu trafic mare. În toate cele trei săptămâni abatorul a lucrat.'],
       did=['Pereți și tavane', 'Colțare și plinte de etanșare', 'Colțare de protecție din inox', 'Uși de silicon pe trecerile cu trafic mare'],
       quote=None),
]

# Filmele (câmpul `video`, cheia vdN) se iau din site/data/films.json, după adresa paginii.

# Ce spune legea, pe domenii. „req” e cerința, „ans” răspunsul din fișa tehnică.
RULES = {
  'alimentar': dict(
    src='Regulamentul (CE) nr. 852/2004, Anexa II, Capitolul II, punctul 1 — traducere de lucru.',
    rows=[
      ('Pardoseli și pereți din materiale <i>impermeabile, neabsorbante, lavabile și netoxice</i>.', 'Porozitate zero. Rășină poliesterică armată cu fibră de sticlă, strat GelCoat continuu. Avizată DSV pentru spații de procesare alimentară.'),
      ('O <i>suprafață netedă</i> până la o înălțime potrivită operațiunilor.', 'Plăci de 1,2–3 m lățime și 2–10 m lungime. Cu cât placa e mai mare, cu atât sunt mai puține îmbinări.'),
      ('Tavane care <i>împiedică acumularea murdăriei</i> și reduc condensul, mucegaiul și desprinderea de particule.', 'Aceeași placă, pe tavan. Fără rost și fără vopsea care să se exfolieze peste linie.'),
      ('Suprafețe ușor de <i>curățat și, unde e nevoie, de dezinfectat</i>.', 'Se spală cu apă, detergent, racletă, abur sau jet sub presiune. Rezistă la dezinfectanții din industria alimentară.'),
    ]),
  'medical': dict(
    src='Anexa 1 la Ordinul MS nr. 1096/2016, art. 3, așa cum îl citează MedClyn.',
    rows=[
      ('Finisaje <i>lavabile</i>, rezistente la dezinfectante și substanțe biocide.', 'GelCoat cu porozitate zero. Își păstrează culoarea la curățare regulată cu dezinfectanți, inclusiv peroxid de hidrogen.'),
      ('<i>Fără asperități</i> care să rețină praful.', 'Placă netedă și antistatică: nu reține praful și microparticulele aduse de ventilația sălii de operație.'),
      ('Fără materiale care, prin montaj, <i>favorizează mucegaiul</i>.', 'Accesoriile etanșează placa față de perete. Umezeala nu ajunge între placă și zid.'),
      ('Unghiuri <i>concave</i> între pardoseală și pereți.', 'Îmbinările perete–pardoseală și perete–tavan se fac cu colțare concave, cu garnitură.'),
    ]),
  'farma': dict(
    src='EU GMP, Anexa 1 (2022), punctul 4.5 — traducere de lucru.',
    rows=[
      ('În camerele curate, toate suprafețele expuse trebuie să fie <i>netede, impermeabile și neîntrerupte</i>, ca să nu elibereze și să nu adune particule sau microorganisme.', 'Placă continuă de până la 10 m, cu porozitate zero. Îmbinările se închid cu baghete tată-mamă, cu garnitură unde se spală cu jet.'),
      ('Suprafețe care rezistă la <i>curățare și dezinfecție repetată</i>.', 'GelCoat-ul își păstrează luciul la dezinfectanți puternici, inclusiv peroxid de hidrogen.'),
      ('Tavane <i>etanșate</i>, ca să nu vină contaminare din spațiul de deasupra.', 'Aceeași placă pe tavan, cu colțare concave etanșe la îmbinarea cu pereții.'),
    ]),
  'cosmetic': dict(
    src='ISO 22716 (Bune practici de fabricație pentru cosmetice), capitolul despre spații; obligatorie prin art. 8 din Regulamentul (CE) nr. 1223/2009.',
    rows=[
      ('Pardoseli, pereți, tavane și ferestre <i>ușor de curățat</i> și, unde e nevoie, de igienizat.', 'Suprafață netedă, fără por, care se spală cu apă, detergent sau abur.'),
      ('Spații <i>ținute curate și în stare bună</i>.', 'Garanție 20 de ani. GelCoat RAL 9010 care nu se îngălbenește la dezinfectanți.'),
    ]),
  'bucatarii': dict(
    src='Regulamentul (CE) nr. 852/2004, Anexa II, Capitolele I și II — se aplică și bucătăriilor restaurantelor și cantinelor.',
    rows=[
      ('Pereți <i>netezi și lavabili</i> în spațiile unde se prepară alimente.', 'Placă fără rosturi, montată peste faianța existentă. Rostul murdar dispare cu totul.'),
      ('Fără <i>condens și mucegai</i>, mai ales în bucătăriile de la subsol.', 'Accesoriile etanșează placa față de perete, deci igrasia din zid nu mai ajunge la suprafață.'),
      ('Suprafețe în <i>stare bună</i>, care rezistă la spălarea zilnică.', 'Rezistă la jet sub presiune, abur și degresanți. Plintă de protecție la înălțimea cărucioarelor.'),
    ]),
  'alte': dict(
    src='Normele de igienă pentru unitățile de învățământ și spațiile publice cer finisaje lavabile în vestiare, grupuri sanitare și bucătării.',
    rows=[
      ('Pereți <i>lavabili</i> în vestiare, dușuri și grupuri sanitare.', 'Placă fără por, spălabilă cu jet. Plăci de 4–5 m montate pe orizontală, fără îmbinări verticale.'),
      ('Finisaje care <i>nu se degradează</i> la spălările repetate.', 'Fără vopsea care să se exfolieze și fără faianță care să cadă.'),
    ]),
}

# Unde se montează, pe domenii (din paginile MedClyn).
WHERE = {
  'alimentar': ['abatoare și săli de tranșare', 'fabrici de mezeluri și carmangerii', 'fabrici de lactate și camere frigorifice', 'brutării și patiserii', 'linii de îmbuteliere', 'vestiare și holuri de producție'],
  'medical':   ['săli de operație', 'camere sterile', 'săli de terapie', 'saloane de supraveghere postoperatorie', 'circuitul lenjeriei și al deșeurilor', 'spălătorii', 'cabinete stomatologice și veterinare', 'laboratoare de analize'],
  'farma':     ['spații de producție', 'laboratoare de cercetare', 'holuri de trecere între zone', 'depozite farmaceutice', 'farmacii'],
  'cosmetic':  ['spații de producție și ambalare', 'laboratoare de formulare', 'depozite de materii prime', 'vestiare și ecluze'],
  'bucatarii': ['bucătării de restaurant', 'bucătării de hotel', 'cantine școlare', 'catering', 'camere frigorifice', 'bucătării la subsol, cu igrasie'],
  'alte':      ['săli de sport și vestiare', 'dușuri și grupuri sanitare', 'cantine', 'spălătorii', 'spații cu umiditate mare'],
}

DOMAIN_COPY = {
  'alimentar': dict(
    title='Plăci antibacteriene pentru industria alimentară, avizate DSV',
    h1='Pereți care trec de DSV și nu se mai revopsesc.',
    lede='Aproape toate halele alimentare din România sunt din panouri sandwich. Vopseaua de pe ele ține 2–3 ani la spălarea zilnică, apoi apare rugina. Placa MedClyn se lipește direct peste panou, fără oprirea liniei.',
    desc='Placare antibacteriană peste panouri sandwich, faianță sau zidărie, pentru abatoare, lactate, mezeluri și brutării. Avizată DSV, garanție 20 de ani, montaj fără oprirea liniei.',
    pain='Panourile sandwich ruginite sunt cea mai des întâlnită problemă pe șantierele MedClyn. Varianta obișnuită e revopsirea: linia oprită, timp de uscare și o vopsea care, după spălările cu presiune, ține iar 2–3 ani.'),
  'medical': dict(
    title='Placare antibacteriană pentru spitale și clinici',
    h1='Sala de operație, placată în trei zile.',
    lede='Vopseaua „lavabilă” și faianța cu rosturi încalcă mai multe puncte din normele Ministerului Sănătății. Placa MedClyn se montează pe sectoare, fără praf, așa că restul spitalului merge mai departe.',
    desc='Pereți și tavane antibacteriene pentru săli de operație, camere sterile și cabinete. Conforme Ordinului MS 1096/2016, montaj pe sectoare, garanție 20 de ani.',
    pain='Cele mai multe clădiri medicale au fost construite înainte de normele actuale. 80% din plăci se taie la depozit după măsurători, deci pe șantier rămân doar montajul și ajustările: puțin praf și sectoare închise pe rând.'),
  'farma': dict(
    title='Pereți și tavane pentru camere curate și fabrici de medicamente',
    h1='Suprafețe netede, impermeabile și neîntrerupte.',
    lede='Formularea e din Anexa 1 GMP pentru camere curate. Swiss Caps, Arena Group și Sanofi au placat cu MedClyn spații de producție și cercetare, pe etape, fără să oprească fabrica.',
    desc='Placare pentru fabrici de medicamente și laboratoare: suprafață continuă, fără por, rezistentă la peroxid de hidrogen. Lucrări la Swiss Caps, Arena Group, Sanofi.',
    pain='În farma, renovarea se face pe etape: în concedii, pe sectoare, cu oameni verificați. Placa se taie la depozit, deci în camera curată intră doar montajul.'),
  'cosmetic': dict(
    title='Placare antibacteriană pentru fabrici de cosmetice (ISO 22716)',
    h1='Același perete ca în farma, pentru producția de cosmetice.',
    lede='Regulamentul european al cosmeticelor cere bune practici de fabricație după ISO 22716, care cere pereți și tavane ușor de curățat și igienizat. MedClyn n-a publicat încă o lucrare în cosmetică; cele mai apropiate sunt cele din farma.',
    desc='Pereți și tavane ușor de igienizat pentru producția de cosmetice, conform ISO 22716. Aceeași placă folosită în fabricile de medicamente.',
    pain='Diferența față de farma ține de procedură, nu de perete: aceeași suprafață fără por, aceleași colțare etanșe, aceeași garanție.'),
  'bucatarii': dict(
    title='Placare pereți bucătării profesionale, peste faianță',
    h1='Peste faianța cu rosturi, fără să închizi bucătăria.',
    lede='Rostul de faianță e primul lucru pe care îl notează controlul în bucătărie. Placa se lipește direct peste faianță. La Ladurée, pe Champs-Élysées, 200 m² s-au făcut într-o noapte, înaintea controlului.',
    desc='Pereți fără rosturi pentru bucătării de restaurant, hotel, cantină și catering, montați peste faianță. Lucru de noapte, fără închiderea bucătăriei.',
    pain='Bucătăriile de restaurant sunt mici, adesea la subsol, și nu au zile libere. De aceea, cele mai multe lucrări MedClyn în bucătării s-au făcut noaptea, cu echipamentele repornite dimineața.'),
  'alte': dict(
    title='Placare lavabilă pentru săli de sport, vestiare și școli',
    h1='Vestiare care se spală cu jetul.',
    lede='Oriunde se spală des și apa ajunge în rosturi, vopseaua se exfoliază și faianța cade. Placa MedClyn vine în lungimi de 4–5 m, deci un perete întreg nu are nicio îmbinare verticală.',
    desc='Pereți lavabili pentru săli de sport, vestiare, dușuri și cantine școlare. Plăci de până la 10 m, fără îmbinări verticale, garanție 20 de ani.',
    pain='La sala de sport a unui liceu, cerința la aviz a fost „cât mai puține îmbinări”. Plăcile de 4–5 m montate pe orizontală au lăsat pereții fără nicio îmbinare verticală.'),
}

# Întrebări pe domenii (folosite și ca FAQPage). Răspunsuri doar din ce a publicat MedClyn.
FAQ_COMMON = [
  ('Trebuie să spargem ce e acum pe pereți?', 'Nu. Placa se lipește peste ce există: cărămidă, tencuială, faianță, zugrăveli, rigips sau panouri sandwich. Doar unde suportul e slab se curăță întâi, ca la Lactate Brădet, ca să nu se piardă garanția.'),
  ('Cât stă producția?', 'Depinde de câte ore îți permiți. La Bona Avis, liniile au mers 8 ore din 10, iar echipa a lucrat după-amiaza și noaptea. La Ursus, Chai 33 și la abatorul din Rennes, linia n-a oprit deloc. Swiss Caps lucrează în concediile colective.'),
  ('Cât costă pe metru pătrat?', 'Placa de 2 mm costă 252,88 lei/m² cu TVA în magazinul MedClyn. Cu accesorii și manoperă, MedClyn calculează aproximativ 350 lei/m², o singură dată pe 20 de ani. Prețul exact vine după măsurătoare.'),
  ('Ce garanție are?', '20 de ani pe materiale și lucrare. Dacă apar probleme la folosire normală, echipa MedClyn înlocuiește porțiunile afectate.'),
  ('Cât de repede se montează?', 'Clinica medicală: 200 m² într-o zi. AYT: 300 m² în 2 zile. Pomarom: 1.200 m² în 4 zile. 80% din plăci se taie la depozitul din Băicoi după măsurători, iar pe șantier rămâne montajul.'),
]
FAQ_DOMAIN = {
  'alimentar': [('Trece de DSV?', 'Placa e avizată de Direcția Sanitar-Veterinară pentru spații de procesare alimentară și răspunde punct cu punct cerințelor din Regulamentul 852/2004, Anexa II.'),
                ('Se poate monta peste panouri sandwich ruginite?', 'Da, ăsta e cel mai des caz: Bona Avis, Safir, Pomarom, Vlasie, Sagrod. Placa se lipește peste panou, iar rugina rămâne închisă sub un strat etanș.')],
  'medical':   [('Ce dezinfectanți suportă?', 'Stratul GelCoat își păstrează culoarea și luciul la curățare regulată cu dezinfectanți puternici, inclusiv peroxid de hidrogen. Pentru produsele voastre exacte, cereți confirmarea odată cu oferta.'),
                ('Se poate lucra pe sectoare?', 'Da. Plăcile se taie la depozit, iar pe șantier rămâne montajul, cu puțin praf. Restul spitalului funcționează normal.')],
  'farma':     [('Se poate lucra doar în concedii?', 'Da. Swiss Caps își renovează fabrica pe etape, în perioadele de concediu, când producția e redusă: 350 m² în 3 zile.'),
                ('Acceptă protocoale de securitate stricte?', 'La Sanofi, toți oamenii MedClyn au fost verificați de serviciile franceze de securitate, iar controlul corporal se făcea la fiecare trecere între sectoare.')],
  'cosmetic':  [('Aveți lucrări în cosmetică?', 'Nu publicate încă. Spațiile cele mai apropiate ca cerințe sunt cele din farma: Swiss Caps, Arena Group și Sanofi.')],
  'bucatarii': [('Se montează peste faianță?', 'Da, direct peste faianța existentă. Rosturile murdare rămân sub placă, sigilate.'),
                ('Putem lucra doar noaptea?', 'Da. La Bianco, în Paris, echipamentele erau oprite seara și repornite dimineața, iar bucătăria gătea normal ziua.')],
  'alte':      [('Cât de lungi sunt plăcile?', 'Între 2 și 10 m, la 1,2–3 m lățime. La sala de sport a unui liceu s-au montat plăci de 4–5 m pe orizontală, fără îmbinări verticale.')],
}

# Ghiduri: pagini scrise pentru căutări reale, cu cifre din lucrări.
GUIDES = [
  dict(slug='cerinte-dsv-pereti-tavane', date='2026-10-02',
       title='Ce verifică DSV la pereți și tavane',
       h1='Ce verifică DSV la pereți și tavane.',
       desc='Cerințele din Regulamentul 852/2004 pentru pereți și tavane în spațiile alimentare, ce notează inspectorul la faianță, vopsea și panouri sandwich și ce trece.',
       lede='Regulamentul nu spune „faianță” și nu spune „vopsea”. Spune ce însușiri trebuie să aibă suprafața. Ce urmează e lista, cu ce notează de obicei inspectorul la fiecare finisaj.'),
  dict(slug='renovare-panouri-sandwich', date='2026-10-02',
       title='Panouri sandwich ruginite: revopsire sau placare?',
       h1='Panouri sandwich ruginite: revopsești sau placezi?',
       desc='De ce vopseaua de pe panourile sandwich ține 2–3 ani în spațiile alimentare, cât costă revopsirea pe 20 de ani și cum se placează peste panou fără oprirea liniei.',
       lede='Mai mult de jumătate din lucrările publicate de MedClyn în România sunt peste panouri sandwich ruginite. Povestea e mereu aceeași: revopsire la 2–3 ani, linia oprită, iar după încă un an vopseaua se exfoliază din nou.'),
  dict(slug='faianta-sau-placi-antibacteriene', date='2026-10-02',
       title='Faianță sau plăci antibacteriene: costul pe 20 de ani',
       h1='Faianță sau placă: cât te costă pe 20 de ani.',
       desc='Comparație pe 20 de ani între vopsea lavabilă, faianță clasică, faianță rectificată și placarea MedClyn: cost pe m², număr de renovări, ce acceptă DSV.',
       lede='Prețul pe metru pătrat din oferta de azi spune puțin. Contează de câte ori refaci peretele în 20 de ani și dacă trece de control între timp. Cifrele de mai jos sunt cele publicate de MedClyn.'),
]

# Comparația pe 20 de ani, din pagina „Ce este MedClyn” a lor.
COMPARE = [
  dict(name='Vopsea lavabilă', m2='≈25 lei', renov='~10 (la 2 ani)', total='min. 250 lei', dsv=False,
       note='Se degradează repede unde se spală des sau trec utilaje. Reparațiile au timp de uscare.'),
  dict(name='Faianță clasică', m2='250 lei', renov='2', total='500 lei', dsv=False,
       note='Are rosturi. Apa intră prin rost în spatele faianței. Reparația oprește de obicei linia.'),
  dict(name='Faianță rectificată antibacteriană', m2='600 lei', renov='0–1', total='600–1.200 lei', dsv=True,
       note='Scumpă, stocuri mici în România, puțini montatori care o pun etanș.'),
  dict(name='Placare MedClyn', m2='350 lei', renov='0 (garanție 20 de ani)', total='350 lei', dsv=True,
       note='Material, accesorii și manoperă. Cost inițial mai mare decât vopseaua.'),
]
